### ISSUE TITLE
Initial load error using "cds watch"

### ISSUE THREAD

**Issue by dracovoldy** [AjitKP/cap-fe-se-ca-de#1]
I cloned the repo, executed one of the webapps and got the following error.
Looks like the SQLite file with data is missing.

SQLITE_ERROR: no such table: localized_orderservice_Orders in:
SELECT count ( 1 ) AS "$count" FROM ( SELECT 1 FROM orderservice_Orders_drafts ALIAS_1 INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON ALIAS_1.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID WHERE filterAdmin.InProcessByUser = ? UNION ALL SELECT 1 FROM localized_orderservice_Orders ALIAS_1 WHERE NOT EXISTS ( SELECT 1 FROM orderservice_Orders_drafts ALIAS_2 INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON ALIAS_2.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID WHERE filterAdmin.InProcessByUser = ? AND ALIAS_1.ID = ALIAS_2.ID ) ) AS orderservice_Orders_drafts

![image](https://user-images.githubusercontent.com/1318151/209436905-2443da83-d3c6-4935-a338-b51c611ccd65.png)

**Comment by dracovoldy** [comment]
On executing the following command `cds` deploy --to sqlite` was able to get the sqlite.db file generated. 
Is it possible for you to update all the csv files to the repo?

**Comment by AjitKP** [comment]
@dracovoldy  Have already provided csv files here: https://github.com/AjitKP/cap-fe-se-ca-de/tree/master/db/data 

when you do cds watch, it is automatically considered. Rest you can create using both Customers and Orders application. 
First create a customer and then can create an order.
